<?xml version="1.0" encoding="UTF-8"?><testrun name="SaveCommandTest.SaveCommandTest_FileNameEmpty" project="Assignment 3" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testcase name="SaveCommandTest_FileNameEmpty" classname="com.usu.command.test.SaveCommandTest" time="66.07">
    <error>com.amazonaws.AmazonClientException: Unable to calculate MD5 hash: &#13;
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1332)&#13;
	at com.usu.drawingGUI.DrawingPalette.save(DrawingPalette.java:158)&#13;
	at com.usu.command.SaveCommand.execute(SaveCommand.java:20)&#13;
	at com.usu.command.test.SaveCommandTest.SaveCommandTest_FileNameEmpty(Unknown Source)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.io.FileNotFoundException: &#13;
	at java.io.FileInputStream.open0(Native Method)&#13;
	at java.io.FileInputStream.open(Unknown Source)&#13;
	at java.io.FileInputStream.&lt;init&gt;(Unknown Source)&#13;
	at com.amazonaws.util.Md5Utils.computeMD5Hash(Md5Utils.java:97)&#13;
	at com.amazonaws.util.Md5Utils.md5AsBase64(Md5Utils.java:104)&#13;
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1329)&#13;
	... 26 more&#13;
&#13;
</error>
  </testcase>
</testrun>
