<?xml version="1.0" encoding="UTF-8"?><testrun name="test" project="Assignment 4" tests="16" started="16" failures="2" errors="0" ignored="0">
  <testsuite name="com.usu.sudokuSolver.utils.test.UtilitiesTest" time="2.892">
    <testcase name="testExportSolution_NullBoard" classname="com.usu.sudokuSolver.utils.test.UtilitiesTest" time="0.0"/>
    <testcase name="testExportSolution_AllCorrect" classname="com.usu.sudokuSolver.utils.test.UtilitiesTest" time="0.0"/>
    <testcase name="testExportSolution_EmptyBoard" classname="com.usu.sudokuSolver.utils.test.UtilitiesTest" time="0.005"/>
    <testcase name="testExportSolution_EmptyFileName" classname="com.usu.sudokuSolver.utils.test.UtilitiesTest" time="2.851"/>
    <testcase name="testExportSolution_NullFileName" classname="com.usu.sudokuSolver.utils.test.UtilitiesTest" time="0.036"/>
  </testsuite>
  <testsuite name="com.usu.sudokuSolver.board.test.SudokuBoardTest" time="0.044">
    <testcase name="testRows" classname="com.usu.sudokuSolver.board.test.SudokuBoardTest" time="0.007"/>
    <testcase name="testGetCell" classname="com.usu.sudokuSolver.board.test.SudokuBoardTest" time="0.003">
      <failure>java.lang.AssertionError: expected: java.lang.Integer&lt;8&gt; but was: java.lang.String&lt;8&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:144)&#13;
	at com.usu.sudokuSolver.board.test.SudokuBoardTest.testGetCell(SudokuBoardTest.java:49)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testSetCell_NullValue" classname="com.usu.sudokuSolver.board.test.SudokuBoardTest" time="0.006"/>
    <testcase name="testColumns" classname="com.usu.sudokuSolver.board.test.SudokuBoardTest" time="0.008"/>
    <testcase name="testSetCell_SymbolNullValue" classname="com.usu.sudokuSolver.board.test.SudokuBoardTest" time="0.008"/>
    <testcase name="testGetCell_NullValue" classname="com.usu.sudokuSolver.board.test.SudokuBoardTest" time="0.006"/>
    <testcase name="testSetCell" classname="com.usu.sudokuSolver.board.test.SudokuBoardTest" time="0.001">
      <failure>java.lang.AssertionError: expected: java.lang.Integer&lt;3&gt; but was: java.lang.String&lt;3&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:144)&#13;
	at com.usu.sudokuSolver.board.test.SudokuBoardTest.testSetCell(SudokuBoardTest.java:68)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
  <testsuite name="com.usu.sudokuSolver.board.test.TestSolver" time="0.755">
    <testcase name="testIsSolved" classname="com.usu.sudokuSolver.board.test.TestSolver" time="0.755"/>
  </testsuite>
  <testsuite name="com.usu.sudokuSolver.board.test.SudokuBoardParserTest" time="0.028">
    <testcase name="testParsingLogic_NullInput" classname="com.usu.sudokuSolver.board.test.SudokuBoardParserTest" time="0.021"/>
    <testcase name="testParsingLogic_Correct" classname="com.usu.sudokuSolver.board.test.SudokuBoardParserTest" time="0.005"/>
    <testcase name="testParsingLogic_EmptyInput" classname="com.usu.sudokuSolver.board.test.SudokuBoardParserTest" time="0.002"/>
  </testsuite>
</testrun>
